version: "3"

services: 

    bot:
        build: .
        depends_on: 
            - database
        volumes: 
            - ./src:/app

    database:
        image: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: olx
